[package]
name = "auto-deploy-server"
version = "0.1.0"
edition = "2021"


[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
sha2 = "0.10"
hmac = "0.12.1"
serde_json = "1.0.82"